### ISSUE TITLE
你好，请问你的框架适用环境

### ISSUE THREAD

**Issue by allenXu317** [pureisle/MicroMVC#2]
我发现php7往上在win下并没有memcached可以用，只有mac或者linux才有。
请问你的框架是只适用于unix环境嘛？

**Comment by pureisle** [comment]
因为在企业生产环境中，基本上都是Linux环境，所以虽然这个项目我这边已经用于六个项目的实际生产了，但是还没有在Windows环境下测试过。

不过我理解Windows下使用应该问题也不大，不能用的类库替换掉应该就可以的。

**Comment by allenXu317** [comment]
嗯嗯好的，谢谢您
